name: Build & Publish to Registry

on:
  workflow_call:
    inputs:
      ### Values from CICD Workflow ###
      REGISTRY:
        required: true
        type: string
        description: 'The Environemnt which should be used.'
      ORGANISATION_NAME:
        type: string
        required: true
        description: 'The Subscription ID which should be used.'

env:
  IMAGE: '${{ inputs.REGISTRY }}/${{ inputs.ORGANISATION_NAME }}/gh-runner'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=raw,latest
            type=sha,prefix=,suffix=,short=true

      - name: Build and push the fred version of the WebApp
        uses: docker/build-push-action@v5.1.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          context: ./gh-runner
          file: ./gh-runner/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

      - name: Display image tag in summary
        run: |
          echo "### Build & release! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Released image:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ${{steps.meta.outputs.tags}}" >> $GITHUB_STEP_SUMMARY